apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ytCcdoh5bi4=,iv:XEBILZOziWFwJuJKWeJ5JnOvRkDFJh06bttWlpP2SJw=,tag:0nJop8Y9wCwaaiL1xUGI0g==,type:str]
    user: ENC[AES256_GCM,data:vk4nSbYxDMg=,iv:2+Phx+3so33d4dlz2xJNVqVCRMvgFJ55/+YjR3NMvNo=,tag:QeZOglMGEXRTxgAlr17GVw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1gemn6ajnne5rf66zjsxqghd232hr72ekjzjs57kxfwjv884dmegs0ylcwp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTkhVUUl0SC9MVURPbEtM
            Y09NSS9kaVdNL0pmUDZLL1Byd1VLL2RFSWhjClRGQm5JL0hGQVJQRVdMMHI0Rk1r
            cmwxY2UyWkt2S29ZWDZGYllnTkl4Um8KLS0tIHgweG1veTRRTVVvZk9SN2NtMWlu
            dFdGU1Fqd2tncGVoUjJEOTdaRUZtSVEKCTZJdBGw+Fu471C4CAlqjoLKUBq8lHkg
            vALQuGRb08MrU+tUa0e3400rltS/MGkMpr/pbu+EkLmePcomMVtXvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-17T21:43:21Z"
    mac: ENC[AES256_GCM,data:w3oNBQ4/SkUCU81K0SpEpI4rmOZdHkMSmJL/cS5K9S4BZwpJdcq8jDfRQmHS0umVKIcw0t8IQQCW26m9uOeMCwWTVezzD7NxfcWCI0c7PwSYAkieHMLXybGIGeicne3gXQb7+qR6HwULzBEJi1Sr8f7A168nydOrUDzuB/pV4mo=,iv:F/G1TYjSkG8i76AAQl4Kxf45lXuRztx5Lspn+eCHWZ4=,tag:H9FTQR/NT8yk6PEfZBON5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
