apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:TMc+eOP9paCUT0jejgryqhlaB2HBdufOo3DwOoH04UGvkxxGIrTnLZM/Sr9zK2ryMr5QzMEOJzcHXcSU+3MiAppOoF1XckVZ3AzSBR9O1SR45WfcyBMSAczqcjtyzw391CarrF10p/TtWSA6rnwxc3CZbeUkC+PjswnsBNfWdsFzDBoHLGE7utlKaGBDw7zCWpQZ/1iYuHTwNgJ/6U0iXb5OB4ait+t9oW1JoAhLPzy/DNeZm7D+zQXw50Bht1wAHl+d0fpHNIkgZcyFn+DRnyT2H1v3OLrBuv0BVZ/FJSmANqqCyhX2YELToFc=,iv:tTQus3XQQmkf+A9NR6cf6z1D7JbAb6KvP/wZ/Wd68gE=,tag:PgnxsDVKmHOvufw7QNuwDA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1gemn6ajnne5rf66zjsxqghd232hr72ekjzjs57kxfwjv884dmegs0ylcwp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveVlKaUxGZnUxTmxBSGZl
            ZlRMVU5JTFJqL1Exa2ZpWEEwZGY5VWlIRlc4CkhuUnM1NjV3S2wwZkRXUWMxVGhG
            SjhVcGNLNVJGaEZ1c0RzMkN3eHhrK0EKLS0tIGEzemFCblBTM3VkcWxxQWs2NXYz
            d2JZSmJaRFhCM0hkSHpEc01ZcEJtVHMKnsUxYDIjVV3mvHNXjyNNT3bfQ9z5nqlg
            fjQHdDqxqC5ZpSkSZNOyrW4lk3yfBRjv+zPQNCRKGwZk5RQn+I4HUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T21:35:44Z"
    mac: ENC[AES256_GCM,data:G9PVsCkdOA6ciCoT4hDBsHwxMFQl9ut6kPpp+QUiWrWqmrNVPzVkSz2n8SySckI3nx7WIixnqiZrRUcAwfHBS6xfTOadyBcVT/PCuyHZ0jsRiOWhx0mR5YZIWMF/HZsyBYW9pnzwU5eqdGGh2UULUSYvi5E6Wy+ZhYoNTPftKUg=,iv:Irh8AtDV80c6tAkmAP8zupHJm5E1dxNDgJo9XkA6mOc=,tag:RNmCDvXxy4hR8H9o1k6QfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
