apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:OmmAy6ViAntuImoBOU8Dv69kMepbpOvhjHLIrBVbi1IKwYkH7Gh6pt2r+Y9ynXK81HlF/uJnxlka1r3qdazKD/bSjldf/wmz5izLPOLX//65CNbR6wUJ2AmxQb1fxw31llvkAfDp+HnI+go9YKU4vqwonqXBG1JEApvptQ==,iv:FC4OEa7/n6MnBcjR3Dn7Wr2APOILVrtzxsla/cD/Avc=,tag:jv6P7Z/4BZRElOZ/1BEsOg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
sops:
    age:
        - recipient: age1gemn6ajnne5rf66zjsxqghd232hr72ekjzjs57kxfwjv884dmegs0ylcwp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eFlsL09sczhtUFhUK1k1
            bUR4algyemtnalo3YU1oMG9jOXcwZk5ZTlV3CkZyWWx5Q21qWllIUkdzc0NNWTFx
            NjR4b0Q5RS9qUjc1UUpiTkc4MnViVkkKLS0tIC9vLzVIUG95bzYrYnVBcmNrbFZi
            TFhWT2dIaWZmOVd1cGtpMUlydkg2OHMKmJhzHvPL636skekRserKfDCHkFW6LT6+
            3PNOXUFZzjT6ufHvIUSRzxxVNHnZqXfMJ/amwtgs6DRN6WMTSjKJwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-26T21:37:30Z"
    mac: ENC[AES256_GCM,data:OuWzSioilUEIwcqp0Hux5Ps71asgbeh6VdOTd3j9m2VNe+ZXbLxA/ZLqAwK+a4zHzL/GCnPqDrFycDIXgkHOVZCW5pRbCH4sKncnNi/HCiMKFKsHXKyXY0R5I0oONVKPr+9JWJI04MP9ZyCdDdSJeIIMtD0KWPYxpoWUR64HE0Q=,iv:BGJHrYrLhkwrw0tlAKRryR57Erlf4XpnrcPrXzLkFQQ=,tag:9DphuDw3ovg94CoHpoXukA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
